### ISSUE TITLE
UI Optimization - Choices on Input Format

### ISSUE THREAD

**Issue by j3soon** [j3soon/whisper-to-input#15]
As suggested by @ijsun (offline): After speaking, provide 3 buttons for different input format:
1. Click the mic button again: This will have the same behavior as GBoard, which will directly input the transcribed text.
2. Click the `return`/`enter` button (icon may be something like ↩, replace the current checkmark icon), which will input the text followed by a newline. This button can also be used when not recording, which will simply input a newline.
3. Click the cancel button (icon may be a ❌, at the left side of the mic button), which will cancel the input.

**Comment by ijsun** [comment]
Great. Thanks,

From: Johnson Sun ***@***.***
Sent: Wednesday, November 29, 2023 8:32 AM
To: j3soon/whisper-to-input ***@***.***>
Cc: 孫英洲 ***@***.***>; Mention ***@***.***>
Subject: [j3soon/whisper-to-input] UI Optimization - Choices on Input Format (Issue #15)


As suggested by @ijsun<https://github.com/ijsun>: After speaking, provide 3 buttons for different input format:

  1.  Click the mic button again: This will have the same behavior as GBoard, which will directly input the transcribed text.
  2.  Click the return/enter button (icon may be something like ↩, replace the current checkmark icon), which will input the text followed by a newline.
  3.  Click the cancel button (icon may be a ❌, at the left side of the mic button), which will cancel the input.
