### ISSUE TITLE
request: publish APK as github release

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [j3soon/whisper-to-input#22]
Hi,

I would love to try your app as I've been looking for a way to use whisper as a keyboard on my degoogled phone for ages. Can you consider publishing the apk in the release of this repo?

Thanks!

**Comment by j3soon** [comment]
Just release v0.1 APK. Please follow the instructions: https://github.com/j3soon/whisper-to-input#installation

**Comment by thiswillbeyourgithub** [comment]
It's awesome thank you very much!
