### ISSUE TITLE
Stopping early when whispering

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [j3soon/whisper-to-input#29]
Hi, this is related to #27 

Having lost my voice recently (shoutout to [speech.sh](https://github.com/thiswillbeyourgithub/speech.sh) I made quickly to speak today) I noticed than whispering to your app makes it stop early during my speech. I think this might be due to a low absolute volume threshold because otherwise the text is detected fine.

Hence, like in #27 I think it would be good to allow disabling / changing the silence threshold / timeout etc.

Thanks a lot!

**Comment by luisherranz** [comment]
I'm also having this issue. I'd rather always have to tap to end the recording.

**Comment by luisherranz** [comment]
It also stops when I stop to think for a while 😄
