### ISSUE TITLE
Add default endpoint

### ISSUE THREAD

**Issue by j3soon** [j3soon/whisper-to-input#37]
Setting up the following endpoint can be a bit of a hassle during a fresh install. Could it be automatically applied when selecting the OpenAI API style request?

```
https://api.openai.com/v1/audio/transcriptions
```

**Comment by SatiMa24** [comment]
I tried that and it didn't work here are my settings and I'm using I just started using the app and I can't get it to to do speech to text
Whisper to input settings

Request style: 
I tried but they don't work
OpenAI API

Whisper Webservice

Endpoint :
I tried this one but no not
https://api.openai.com/v1/audio/transcriptions

This one doesn't work
http://<SERVER_IP>:9000/asr
  
Language Code: 
I just enter the main language I'm using I'm not too sure what I have to enter here
ENGLISH

API:
 sk-...xxxx
     ```

Auto recording: No


It it won't work because it's asking this

Unable to resolve host
No address 
  <sever_ip>

Or I try again and it says this/ Unexpected char........

Or I try again and it's like this/
Error message invalid
